const wa='https://wa.me/5562998230185?text=';
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa+encodeURIComponent(a.dataset.wa);a.target='_blank';a.rel='noopener noreferrer'});
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');menu.textContent='☰'}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');menu.textContent=open?'×':'☰'});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
const schedule=[[['06:30','Funcional','Camila • 45 min'],['12:15','Bike indoor','Bruno • 45 min'],['18:30','Dança','Camila • 50 min'],['19:30','Funcional','Rafael • 45 min']],[['07:00','Bike indoor','Bruno • 45 min'],['12:15','Mobilidade','Camila • 30 min'],['18:30','Funcional','Rafael • 45 min'],['19:30','Bike indoor','Bruno • 45 min']],[['06:30','Funcional','Camila • 45 min'],['12:15','Bike indoor','Bruno • 45 min'],['18:30','Dança','Camila • 50 min'],['19:30','Mobilidade','Rafael • 30 min']],[['07:00','Bike indoor','Bruno • 45 min'],['12:15','Mobilidade','Camila • 30 min'],['18:30','Funcional','Rafael • 45 min'],['19:30','Dança','Camila • 50 min']],[['06:30','Funcional','Camila • 45 min'],['12:15','Bike indoor','Bruno • 45 min'],['18:00','Dança','Camila • 50 min'],['19:00','Funcional','Rafael • 45 min']],[['08:00','Funcional','Rafael • 45 min'],['09:00','Bike indoor','Bruno • 45 min'],['10:00','Dança','Camila • 50 min'],['11:00','Mobilidade','Camila • 30 min']]];
function showDay(i){document.querySelector('#classes').innerHTML=schedule[i].map(([time,name,coach])=>`<article class="class"><time>${time}</time><h3>${name}</h3><p>${coach}</p></article>`).join('');document.querySelectorAll('[data-day]').forEach(b=>{const active=Number(b.dataset.day)===i;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>showDay(Number(b.dataset.day))));showDay(0);
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
